// <auto-generated />
using System;
using FitnessTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250709112314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Api.Models.Antrenman", b =>
                {
                    b.Property<int>("AntrenmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AntrenmanID"));

                    b.Property<DateTime>("AntrenmanTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AntrenmanID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Antrenmanlar");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.AntrenmanDetay", b =>
                {
                    b.Property<int>("DetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetayID"));

                    b.Property<decimal>("Agirlik")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("AntrenmanID")
                        .HasColumnType("int");

                    b.Property<int>("EgzersizID")
                        .HasColumnType("int");

                    b.Property<int>("SetSayisi")
                        .HasColumnType("int");

                    b.Property<int>("TekrarSayisi")
                        .HasColumnType("int");

                    b.HasKey("DetayID");

                    b.HasIndex("AntrenmanID");

                    b.HasIndex("EgzersizID");

                    b.ToTable("AntrenmanDetaylari");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.BeslenmeGunlugu", b =>
                {
                    b.Property<int>("BeslenmeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeslenmeID"));

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<decimal>("Karbonhidrat")
                        .HasColumnType("decimal(5, 1)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("OgunTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(5, 1)");

                    b.Property<decimal>("Yag")
                        .HasColumnType("decimal(5, 1)");

                    b.Property<string>("YiyecekAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BeslenmeID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("BeslenmeGunlukleri");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Egzersiz", b =>
                {
                    b.Property<int>("EgzersizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgzersizID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KasGrubu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EgzersizID");

                    b.ToTable("Egzersizler");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.EgzersizFotografi", b =>
                {
                    b.Property<int>("FotografID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FotografID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EgzersizID")
                        .HasColumnType("int");

                    b.Property<string>("FotoURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("FotografID");

                    b.HasIndex("EgzersizID");

                    b.ToTable("EgzersizFotograflari");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Hedef", b =>
                {
                    b.Property<int>("HedefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HedefID"));

                    b.Property<decimal>("BaslangicDegeri")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HedefDeger")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("HedefTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.HasKey("HedefID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Hedefler");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.IlerlemeTakibi", b =>
                {
                    b.Property<int>("IlerlemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlerlemeID"));

                    b.Property<decimal?>("KasKutlesiKG")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("KiloKG")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("YagOrani")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("IlerlemeID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("IlerlemeTakibiKayitlari");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BoyCM")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("GuncelKiloKG")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("KocID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Antrenman", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.AntrenmanDetay", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Antrenman", "Antrenman")
                        .WithMany()
                        .HasForeignKey("AntrenmanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Api.Models.Egzersiz", "Egzersiz")
                        .WithMany()
                        .HasForeignKey("EgzersizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenman");

                    b.Navigation("Egzersiz");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.BeslenmeGunlugu", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.EgzersizFotografi", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Egzersiz", "Egzersiz")
                        .WithMany()
                        .HasForeignKey("EgzersizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egzersiz");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Hedef", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.IlerlemeTakibi", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
